
//------------------------------------------------------------------------------
// <auto-generated>
//     This file was automatically generated by Unity.Entities.Editor.BurstInteropCodeGenerator
//     Any changes you make here will be overwritten
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     To update this file, use the "DOTS -> Regenerate Burst Interop" menu option.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Unity.Burst;
using Unity.Collections;
using System.Runtime.InteropServices;

namespace Unity.Entities
{
     unsafe partial struct ECBInterop
    {

#if !(UNITY_DOTSRUNTIME || (UNITY_2020_1_OR_NEWER && UNITY_IOS))
        static bool _initialized = false;

        [BurstDiscard]
        private static void CheckDelegate(ref bool useDelegate)
        {
            //@TODO: This should use BurstCompiler.IsEnabled once that is available as an efficient API.
            useDelegate = true;
        }

        private static bool UseDelegate()
        {
            bool result = false;
            CheckDelegate(ref result);
            return result;
        }

        private delegate void _dlg_RemoveManagedReferences(EntityDataAccess* mgr, int* sharedIndex, int count);
        private static object _gcDefeat_RemoveManagedReferences;
        private struct TagType_RemoveManagedReferences {};
        private static readonly SharedStatic<IntPtr> _bfp_RemoveManagedReferences = SharedStatic<IntPtr>.GetOrCreate<TagType_RemoveManagedReferences>();

#endif

        [NotBurstCompatible]
        internal static void Initialize()
        {
#if !(UNITY_DOTSRUNTIME || (UNITY_2020_1_OR_NEWER && UNITY_IOS))
            if (_initialized)
                return;
            _initialized = true;
        _dlg_RemoveManagedReferences delegateObject = _wrapper_RemoveManagedReferences;
        _gcDefeat_RemoveManagedReferences = delegateObject;
        _bfp_RemoveManagedReferences.Data = Marshal.GetFunctionPointerForDelegate(delegateObject);

#endif
        }


        internal static void RemoveManagedReferences (EntityDataAccess* mgr, int* sharedIndex, int count)
        {
#if !(UNITY_DOTSRUNTIME || (UNITY_2020_1_OR_NEWER && UNITY_IOS))
            if (!UseDelegate())
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if( _bfp_RemoveManagedReferences.Data == IntPtr.Zero)
                    throw new InvalidOperationException("Burst Interop Classes must be initialized manually");
#endif

                var fp = new FunctionPointer<_dlg_RemoveManagedReferences>(_bfp_RemoveManagedReferences.Data);
                fp.Invoke(mgr, sharedIndex, count);
                return;
            }
#endif
            _RemoveManagedReferences(mgr, sharedIndex, count);
        }

#if !(UNITY_DOTSRUNTIME || (UNITY_2020_1_OR_NEWER && UNITY_IOS))
        [MonoPInvokeCallback(typeof(_dlg_RemoveManagedReferences))]
#endif
        private static void _wrapper_RemoveManagedReferences (EntityDataAccess* mgr, int* sharedIndex, int count)
        {
            _RemoveManagedReferences(mgr, sharedIndex, count);
        }


    }
}
