
//------------------------------------------------------------------------------
// <auto-generated>
//     This file was automatically generated by Unity.Entities.Editor.BurstInteropCodeGenerator
//     Any changes you make here will be overwritten
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     To update this file, use the "DOTS -> Regenerate Burst Interop" menu option.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Unity.Burst;
using Unity.Collections;
using System.Runtime.InteropServices;
using Unity.Collections.LowLevel.Unsafe;

namespace Unity.Entities
{
     unsafe partial struct ECBInterop
    {

#if !UNITY_IOS

        [BurstDiscard]
        private static void CheckDelegate(ref bool useDelegate)
        {
            //@TODO: This should use BurstCompiler.IsEnabled once that is available as an efficient API.
            useDelegate = true;
        }

        private static bool UseDelegate()
        {
            bool result = false;
            CheckDelegate(ref result);
            return result;
        }

        static class Managed
        {
            public static bool _initialized = false;

            public delegate void _dlg_ProcessChainChunk(IntPtr walker, int processorType, IntPtr chainStates, int currentChain, int nextChain);
            public static _dlg_ProcessChainChunk _bfp_ProcessChainChunk;
            public delegate void _dlg_RemoveManagedReferences(IntPtr mgr, IntPtr sharedIndex, int count);
            public static object _gcDefeat_RemoveManagedReferences;
        }

        struct TagType_RemoveManagedReferences {};
        public static readonly SharedStatic<IntPtr> _bfp_RemoveManagedReferences = SharedStatic<IntPtr>.GetOrCreate<TagType_RemoveManagedReferences>();

#endif

        [NotBurstCompatible]
        internal static void Initialize()
        {
#if !UNITY_IOS
            if (Managed._initialized)
                return;
            Managed._initialized = true;
            Managed._bfp_ProcessChainChunk = BurstCompiler.CompileFunctionPointer<Managed._dlg_ProcessChainChunk>(_mono_to_burst_ProcessChainChunk).Invoke;
        {
            Managed._dlg_RemoveManagedReferences delegateObject = _wrapper_RemoveManagedReferences;
            Managed._gcDefeat_RemoveManagedReferences = delegateObject;
            _bfp_RemoveManagedReferences.Data = Marshal.GetFunctionPointerForDelegate(delegateObject);
        }

#endif
        }

        internal  static void ProcessChainChunk (void* walker, int processorType, ECBChainPlaybackState* chainStates, int currentChain, int nextChain)
        {
#if !UNITY_IOS
            if (UseDelegate())
            {
                _forward_mono_ProcessChainChunk(walker, processorType, chainStates, currentChain, nextChain);
                return;
            }
#endif

            _ProcessChainChunk(walker, processorType, chainStates, currentChain, nextChain);
        }

#if !UNITY_IOS
        [BurstCompile]
        [MonoPInvokeCallback(typeof(Managed._dlg_ProcessChainChunk))]
        private static void _mono_to_burst_ProcessChainChunk(IntPtr walker, int processorType, IntPtr chainStates, int currentChain, int nextChain)
        {
            _ProcessChainChunk((void*)walker, processorType, (ECBChainPlaybackState*)chainStates, currentChain, nextChain);
        }

        [BurstDiscard]
        private static void _forward_mono_ProcessChainChunk(void* walker, int processorType, ECBChainPlaybackState* chainStates, int currentChain, int nextChain)
        {
            Managed._bfp_ProcessChainChunk((IntPtr) walker, processorType, (IntPtr) chainStates, currentChain, nextChain);
        }
#endif


        internal static void RemoveManagedReferences (EntityDataAccess* mgr, int* sharedIndex, int count)
        {
#if !UNITY_IOS
            if (!UseDelegate())
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if( _bfp_RemoveManagedReferences.Data == IntPtr.Zero)
                    throw new InvalidOperationException("Burst Interop Classes must be initialized manually");
#endif

                var fp = new FunctionPointer<Managed._dlg_RemoveManagedReferences>(_bfp_RemoveManagedReferences.Data);
                fp.Invoke((IntPtr) mgr, (IntPtr) sharedIndex, count);
                return;
            }
#endif
            _RemoveManagedReferences(mgr, sharedIndex, count);
        }

#if !UNITY_IOS
        [MonoPInvokeCallback(typeof(Managed._dlg_RemoveManagedReferences))]
#endif
        private static void _wrapper_RemoveManagedReferences (IntPtr mgr, IntPtr sharedIndex, int count)
        {
            _RemoveManagedReferences((EntityDataAccess*)mgr, (int*)sharedIndex, count);
        }


    }
}
