//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.Entities.Editor
{
    using System;


    public partial class BurstInteropCodeGenerator : CodeGeneratorBase
    {
        public override string TransformText()
        {
            this.GenerationEnvironment = null;

            #line 2 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n//-----------------------------------------------------------------------------" +
                "-\r\n// <auto-generated>\r\n//     This file was automatically generated by ");

            #line default
            #line hidden

            #line 5 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetType()));

            #line default
            #line hidden

            #line 5 "BurstInteropCodeGenerator.tt"
            this.Write(@"
//     Any changes you make here will be overwritten
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     To update this file, use the ""DOTS -> Regenerate Burst Interop"" menu option.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Unity.Burst;

namespace ");

            #line default
            #line hidden

            #line 19 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructType.Namespace));

            #line default
            #line hidden

            #line 19 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n{\r\n    ");

            #line default
            #line hidden

            #line 21 "BurstInteropCodeGenerator.tt"
            if (StructType.IsPublic)
            {
            #line default
            #line hidden

            #line 22 "BurstInteropCodeGenerator.tt"
                this.Write("public");

            #line default
            #line hidden

            #line 22 "BurstInteropCodeGenerator.tt"
            }

            #line default
            #line hidden

            #line 23 "BurstInteropCodeGenerator.tt"
            this.Write(" unsafe partial struct ");

            #line default
            #line hidden

            #line 23 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(StructType.Name));

            #line default
            #line hidden

            #line 23 "BurstInteropCodeGenerator.tt"
            this.Write(@"
    {

#if !(NET_DOTS || (UNITY_2020_1_OR_NEWER && UNITY_IOS))
        static bool _initialized = false;

        [BurstDiscard]
        private static void CheckMono(ref bool isMono)
        {
            isMono = true;
        }

        private static bool IsMono()
        {
            bool result = false;
            CheckMono(ref result);
            return result;
        }

");

            #line default
            #line hidden

            #line 42 "BurstInteropCodeGenerator.tt"

            foreach (var method in Methods)
            {
            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write("        private delegate ");

            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ReturnType(method)));

            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write(" _dlg");

            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write("(");

            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Prototype(method)));

            #line default
            #line hidden

            #line 46 "BurstInteropCodeGenerator.tt"
                this.Write(");\r\n        private static _dlg");

            #line default
            #line hidden

            #line 47 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 47 "BurstInteropCodeGenerator.tt"
                this.Write(" _bfp");

            #line default
            #line hidden

            #line 47 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 47 "BurstInteropCodeGenerator.tt"
                this.Write(";\r\n");

            #line default
            #line hidden

            #line 48 "BurstInteropCodeGenerator.tt"
            }

            #line default
            #line hidden

            #line 49 "BurstInteropCodeGenerator.tt"
            this.Write("#endif\r\n\r\n        public static void Initialize()\r\n        {\r\n#if !(NET_DOTS || (" +
                "UNITY_2020_1_OR_NEWER && UNITY_IOS))\r\n            if (_initialized)\r\n           " +
                "     return;\r\n            _initialized = true;\r\n");

            #line default
            #line hidden

            #line 57 "BurstInteropCodeGenerator.tt"
            foreach (var method in Methods)
            {
            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write("            _bfp");

            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write(" = BurstCompiler.CompileFunctionPointer<_dlg");

            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write(">(_mono_to_burst");

            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 58 "BurstInteropCodeGenerator.tt"
                this.Write(").Invoke;\r\n");

            #line default
            #line hidden

            #line 59 "BurstInteropCodeGenerator.tt"
            }

            #line default
            #line hidden

            #line 60 "BurstInteropCodeGenerator.tt"
            this.Write("#endif\r\n        }\r\n\r\n");

            #line default
            #line hidden

            #line 63 "BurstInteropCodeGenerator.tt"
            foreach (var method in Methods)
            {
            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write("        public static ");

            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ReturnType(method)));

            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write(" ");

            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name.Substring(1)));

            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write(" (");

            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Prototype(method)));

            #line default
            #line hidden

            #line 64 "BurstInteropCodeGenerator.tt"
                this.Write(")\r\n        {\r\n#if !(NET_DOTS || (UNITY_2020_1_OR_NEWER && UNITY_IOS))\r\n          " +
                    "  if (IsMono())\r\n            {\r\n");

            #line default
            #line hidden

            #line 69 "BurstInteropCodeGenerator.tt"
                if (method.ReturnType == typeof(void))
                {
            #line default
            #line hidden

            #line 70 "BurstInteropCodeGenerator.tt"
                    this.Write("                _forward_mono");

            #line default
            #line hidden

            #line 70 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 70 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 70 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 70 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n                return;\r\n");

            #line default
            #line hidden

            #line 72 "BurstInteropCodeGenerator.tt"
                }
                else
                {
            #line default
            #line hidden

            #line 73 "BurstInteropCodeGenerator.tt"
                    this.Write("                var _retval = default(");

            #line default
            #line hidden

            #line 73 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(ReturnType(method)));

            #line default
            #line hidden

            #line 73 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n                _forward_mono");

            #line default
            #line hidden

            #line 74 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 74 "BurstInteropCodeGenerator.tt"
                    this.Write("(ref _retval, ");

            #line default
            #line hidden

            #line 74 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 74 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n                return _retval;\r\n");

            #line default
            #line hidden

            #line 76 "BurstInteropCodeGenerator.tt"
                }

            #line default
            #line hidden

            #line 77 "BurstInteropCodeGenerator.tt"
                this.Write("            }\r\n#endif\r\n\r\n");

            #line default
            #line hidden

            #line 80 "BurstInteropCodeGenerator.tt"
                if (method.ReturnType == typeof(void))
                {
            #line default
            #line hidden

            #line 81 "BurstInteropCodeGenerator.tt"
                    this.Write("            ");

            #line default
            #line hidden

            #line 81 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 81 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 81 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 81 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n");

            #line default
            #line hidden

            #line 82 "BurstInteropCodeGenerator.tt"
                }
                else
                {
            #line default
            #line hidden

            #line 83 "BurstInteropCodeGenerator.tt"
                    this.Write("            return ");

            #line default
            #line hidden

            #line 83 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 83 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 83 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 83 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n");

            #line default
            #line hidden

            #line 84 "BurstInteropCodeGenerator.tt"
                }

            #line default
            #line hidden

            #line 85 "BurstInteropCodeGenerator.tt"
                this.Write("        }\r\n\r\n#if !(NET_DOTS || (UNITY_2020_1_OR_NEWER && UNITY_IOS))\r\n        [Bu" +
                    "rstCompile]\r\n        [MonoPInvokeCallback(typeof(_dlg");

            #line default
            #line hidden

            #line 89 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 89 "BurstInteropCodeGenerator.tt"
                this.Write("))]\r\n        private static ");

            #line default
            #line hidden

            #line 90 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(ReturnType(method)));

            #line default
            #line hidden

            #line 90 "BurstInteropCodeGenerator.tt"
                this.Write(" _mono_to_burst");

            #line default
            #line hidden

            #line 90 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 90 "BurstInteropCodeGenerator.tt"
                this.Write("(");

            #line default
            #line hidden

            #line 90 "BurstInteropCodeGenerator.tt"
                this.Write(this.ToStringHelper.ToStringWithCulture(Prototype(method)));

            #line default
            #line hidden

            #line 90 "BurstInteropCodeGenerator.tt"
                this.Write(")\r\n        {\r\n");

            #line default
            #line hidden

            #line 92 "BurstInteropCodeGenerator.tt"
                if (method.ReturnType == typeof(void))
                {
            #line default
            #line hidden

            #line 93 "BurstInteropCodeGenerator.tt"
                    this.Write("            ");

            #line default
            #line hidden

            #line 93 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 93 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 93 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 93 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n");

            #line default
            #line hidden

            #line 94 "BurstInteropCodeGenerator.tt"
                }
                else
                {
            #line default
            #line hidden

            #line 95 "BurstInteropCodeGenerator.tt"
                    this.Write("            return ");

            #line default
            #line hidden

            #line 95 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 95 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 95 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 95 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n");

            #line default
            #line hidden

            #line 96 "BurstInteropCodeGenerator.tt"
                }

            #line default
            #line hidden

            #line 97 "BurstInteropCodeGenerator.tt"
                this.Write("        }\r\n\r\n        [BurstDiscard]\r\n");

            #line default
            #line hidden

            #line 100 "BurstInteropCodeGenerator.tt"
                if (method.ReturnType == typeof(void))
                {
            #line default
            #line hidden

            #line 101 "BurstInteropCodeGenerator.tt"
                    this.Write("        private static void _forward_mono");

            #line default
            #line hidden

            #line 101 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 101 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 101 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(Prototype(method)));

            #line default
            #line hidden

            #line 101 "BurstInteropCodeGenerator.tt"
                    this.Write(")\r\n");

            #line default
            #line hidden

            #line 102 "BurstInteropCodeGenerator.tt"
                }
                else
                {
            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write("        private static void _forward_mono");

            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write("(ref ");

            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(ReturnType(method)));

            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write(" _retval, ");

            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(Prototype(method)));

            #line default
            #line hidden

            #line 103 "BurstInteropCodeGenerator.tt"
                    this.Write(")\r\n");

            #line default
            #line hidden

            #line 104 "BurstInteropCodeGenerator.tt"
                }

            #line default
            #line hidden

            #line 105 "BurstInteropCodeGenerator.tt"
                this.Write("        {\r\n");

            #line default
            #line hidden

            #line 106 "BurstInteropCodeGenerator.tt"
                if (method.ReturnType == typeof(void))
                {
            #line default
            #line hidden

            #line 107 "BurstInteropCodeGenerator.tt"
                    this.Write("            _bfp");

            #line default
            #line hidden

            #line 107 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 107 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 107 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 107 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n");

            #line default
            #line hidden

            #line 108 "BurstInteropCodeGenerator.tt"
                }
                else
                {
            #line default
            #line hidden

            #line 109 "BurstInteropCodeGenerator.tt"
                    this.Write("            _retval = _bfp");

            #line default
            #line hidden

            #line 109 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));

            #line default
            #line hidden

            #line 109 "BurstInteropCodeGenerator.tt"
                    this.Write("(");

            #line default
            #line hidden

            #line 109 "BurstInteropCodeGenerator.tt"
                    this.Write(this.ToStringHelper.ToStringWithCulture(CallArgs(method)));

            #line default
            #line hidden

            #line 109 "BurstInteropCodeGenerator.tt"
                    this.Write(");\r\n");

            #line default
            #line hidden

            #line 110 "BurstInteropCodeGenerator.tt"
                }

            #line default
            #line hidden

            #line 111 "BurstInteropCodeGenerator.tt"
                this.Write("        }\r\n#endif\r\n\r\n");

            #line default
            #line hidden

            #line 114 "BurstInteropCodeGenerator.tt"
            }

            #line default
            #line hidden

            #line 115 "BurstInteropCodeGenerator.tt"
            this.Write("    }\r\n}\r\n");

            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }

        public override void Initialize()
        {
            base.Initialize();
        }
    }
}
