using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("Unity.Entities.Runtime.Build")]
[assembly: InternalsVisibleTo("Unity.Entities.Editor")]
[assembly: InternalsVisibleTo("Unity.Entities.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Scenes.Editor.Tests")]
[assembly: InternalsVisibleTo("Unity.Scenes.Editor.PerformanceTests")]
[assembly: InternalsVisibleTo("Unity.Scenes.Hybrid.Tests")]
[assembly: InternalsVisibleTo("Unity.Samples.Tests")]
[assembly: InternalsVisibleTo("Unity.Entities.Runtime.Build")]
[assembly: InternalsVisibleTo("Unity.Environment.Tests")]
[assembly: InternalsVisibleTo("EnvTestProject.Tests.Editor")]
[assembly: InternalsVisibleTo("Unity.Scenes.PlayerTests")]
[assembly: InternalsVisibleTo("Unity.Entities.Baking.PerformanceTests")]
[assembly: InternalsVisibleTo("Unity.Environment.Baking")]
[assembly: InternalsVisibleTo("Unity.Entities.Hybrid.Tests")]
[assembly: InternalsVisibleTo("Unity.Scenes.Hybrid.Tests.Playmode")]
[assembly: InternalsVisibleTo("Tests.Playmode")]
